### ISSUE TITLE
Enable functionality to management the Discount Percentage 

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempierePOS#43]
Now when the quantity , Unit Price and Discount Percentage are change the Table Panel change

**Comment by marcalwestf** [comment]
it is still missing in ZK

**Comment by marcalwestf** [comment]
Now it works partially in ZK: when I change the values in the fields, and change the focus or hit the TAB key, the value of the field is adopted by the grid. 
I wrote "partially" because this is not the case when the key ENTER (CR) is hit. I think that also by hitting the ENTER key, the value of the field should be adopted by the grid.

**Comment by marcalwestf** [comment]
As of today, not even the TAB key works in ZK.
Swing works OK.

**Comment by marcalwestf** [comment]
With commit a83d2e7054fcce48c0c9c6474c3ad39d14cb7ebd , it is now possible to set discount.
Closing issue
